name: Deploy Development
on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api.development.yml"
    branches:
      - main

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: cd api && yarn install
      - name: Lint
        run: cd api && yarn lint
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_REGISTRY_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api
          platforms: linux/amd64
          push: true
          tags: oww/api:development
