name: Deploy Development
on:
  push:
    paths:
      - "api/**"
    branches:
      - main

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: cd api && npm run install
      - name: Lint
        run: cd api && npm run lint
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_REGISTRY_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            oww/api:development
            oww/api:${{ steps.vars.outputs.sha_short }}
